<a href="https://colab.research.google.com/github/JonghyeonWon/20261RCOSE32200/blob/main/subject2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
train = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/data/2_train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/data/2_test.csv')

train

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,6045,A,Flight,4,3,266.0,5,high,F,5,1590,0
1,44,F,Ship,3,1,174.0,2,low,M,44,1556,1
2,7940,F,Road,4,1,154.0,10,high,M,10,5674,1
3,1596,F,Ship,4,3,158.0,3,medium,F,27,1207,1
4,4395,A,Flight,5,3,175.0,3,low,M,7,4833,1
...,...,...,...,...,...,...,...,...,...,...,...,...
6593,8610,F,Road,5,2,221.0,6,medium,M,4,1952,1
6594,3390,F,Ship,4,5,256.0,3,medium,M,10,4504,1
6595,5150,F,Ship,3,1,217.0,4,medium,F,1,5761,1
6596,3950,F,Road,4,5,174.0,3,medium,F,8,5576,0
6597,5969,C,Ship,6,2,257.0,4,medium,M,1,1513,0

In [ ]:
train.isnull().sum()

ID                     0
Warehouse_block        0
Mode_of_Shipment       5
Customer_care_calls    0
Customer_rating        0
Cost_of_the_Product    3
Prior_purchases        0
Product_importance     0
Gender                 0
Discount_offered       0
Weight_in_gms          0
Reached.on.Time_Y.N    0
dtype: int64

In [ ]:
train.select_dtypes(include = 'object')

,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Product_importance,Gender
0,A,Flight,4,high,F
1,F,Ship,3,low,M
2,F,Road,4,high,M
3,F,Ship,4,medium,F
4,A,Flight,5,low,M
...,...,...,...,...,...
6593,F,Road,5,medium,M
6594,F,Ship,4,medium,M
6595,F,Ship,3,medium,F
6596,F,Road,4,medium,F
6597,C,Ship,6,medium,M

In [ ]:
for col in train.select_dtypes(include = 'object').columns:
  print(col)
  print(train[col].value_counts())
  print('\n\n')

Warehouse_block
Warehouse_block
F    2262
B    1116
A    1090
D    1069
C    1061
Name: count, dtype: int64



Mode_of_Shipment
Mode_of_Shipment
Ship      4507
Flight    1066
Road      1020
Name: count, dtype: int64



Customer_care_calls
Customer_care_calls
4     2115
3     1919
5     1403
6      604
2      404
$7     153
Name: count, dtype: int64



Product_importance
Product_importance
low       3162
medium    2866
high       570
Name: count, dtype: int64



Gender
Gender
F    3311
M    3287
Name: count, dtype: int64

In [ ]:
train.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,6598.0,5476.977266,3172.946154,1.0,2731.25,5476.0,8187.75,10998.0
Customer_rating,6598.0,2.991361,1.409624,1.0,2.00,3.0,4.00,5.0
Cost_of_the_Product,6595.0,210.409249,48.262527,96.0,170.00,214.0,251.00,310.0
Prior_purchases,6598.0,3.577751,1.511394,2.0,3.00,3.0,4.00,10.0
Discount_offered,6598.0,13.353592,16.187267,1.0,4.00,7.0,10.00,65.0
Weight_in_gms,6598.0,3604.191119,1635.697627,1001.0,1834.25,4119.5,5027.50,7684.0
Reached.on.Time_Y.N,6598.0,0.596696,0.490598,0.0,0.00,1.0,1.00,1.0

In [ ]:
train.isnull().sum()

ID                     0
Warehouse_block        0
Mode_of_Shipment       5
Customer_care_calls    0
Customer_rating        0
Cost_of_the_Product    3
Prior_purchases        0
Product_importance     0
Gender                 0
Discount_offered       0
Weight_in_gms          0
Reached.on.Time_Y.N    0
dtype: int64

In [ ]:
train_pre = train.copy()
test_pre = test.copy()

In [ ]:
train_pre['Mode_of_Shipment'] = train_pre['Mode_of_Shipment'].fillna(train_pre['Mode_of_Shipment'].value_counts().index[0])
train_pre['Cost_of_the_Product'] = train_pre['Cost_of_the_Product'].fillna(train_pre['Cost_of_the_Product'].mean())
train_pre.isnull().sum()

ID                     0
Warehouse_block        0
Mode_of_Shipment       0
Customer_care_calls    0
Customer_rating        0
Cost_of_the_Product    0
Prior_purchases        0
Product_importance     0
Gender                 0
Discount_offered       0
Weight_in_gms          0
Reached.on.Time_Y.N    0
dtype: int64

In [ ]:
train_pre['Customer_care_calls'] = train_pre['Customer_care_calls'].str.replace('$', '').astype('int')

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [ ]:
# simple
x = train_pre.drop(columns = ['Reached.on.Time_Y.N', 'ID'])
y = train_pre['Reached.on.Time_Y.N']

x_dummies = pd.get_dummies(x)

x_train, x_val, y_train, y_val = train_test_split(x_dummies, y, test_size = 0.3, random_state = 1)

rf = RandomForestClassifier()
rf.fit(x_train, y_train)
rf_predict = rf.predict(x_val)

f1_score(y_val, rf_predict)

test_pre = test.copy()
test_pre = test_pre.drop(columns = ['ID'])
test_pre['Customer_care_calls'] = test_pre['Customer_care_calls'].str.replace('$', '').astype('int')

test_dum = pd.get_dummies(test_pre)
rf_test_predict = rf.predict(test_dum)

pd.DataFrame(rf_test_predict, columns = ['pred'])

      pred
0        1
1        0
2        0
3        0
4        1
...    ...
4396     1
4397     0
4398     0
4399     0
4400     1

[4401 rows x 1 columns]

In [ ]:
train_pre

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,6045,A,Flight,4,3,266.0,5,high,F,5,1590,0
1,44,F,Ship,3,1,174.0,2,low,M,44,1556,1
2,7940,F,Road,4,1,154.0,10,high,M,10,5674,1
3,1596,F,Ship,4,3,158.0,3,medium,F,27,1207,1
4,4395,A,Flight,5,3,175.0,3,low,M,7,4833,1
...,...,...,...,...,...,...,...,...,...,...,...,...
6593,8610,F,Road,5,2,221.0,6,medium,M,4,1952,1
6594,3390,F,Ship,4,5,256.0,3,medium,M,10,4504,1
6595,5150,F,Ship,3,1,217.0,4,medium,F,1,5761,1
6596,3950,F,Road,4,5,174.0,3,medium,F,8,5576,0
6597,5969,C,Ship,6,2,257.0,4,medium,M,1,1513,0

In [ ]:
# 라벨 인코딩
train_pre = train.copy()
train_pre['Mode_of_Shipment'] = train_pre['Mode_of_Shipment'].fillna(train_pre['Mode_of_Shipment'].value_counts().index[0])
train_pre['Cost_of_the_Product'] = train_pre['Cost_of_the_Product'].fillna(train_pre['Cost_of_the_Product'].mean())
train_pre['Customer_care_calls'] = train_pre['Customer_care_calls'].str.replace('$', '').astype('int')

le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()
le4 = LabelEncoder()

train_pre['Warehouse_block'] = le1.fit_transform(train_pre['Warehouse_block'])
train_pre['Mode_of_Shipment'] = le2.fit_transform(train_pre['Mode_of_Shipment'])
train_pre['Product_importance'] = le3.fit_transform(train_pre['Product_importance'])
train_pre['Gender'] = le4.fit_transform(train_pre['Gender'])

x = train_pre.drop(columns = ['Reached.on.Time_Y.N', 'ID'])
y = train_pre['Reached.on.Time_Y.N']

x_train, x_val, y_train, y_val = train_test_split(x, y, test_size = 0.33, random_state = 1)

rf = RandomForestClassifier()
rf.fit(x_train, y_train)
rf_predict = rf.predict(x_val)

f1_score(y_val, rf_predict)

0.6938607334157396

In [ ]:
# test 전처리
test_pre = test.copy()
test_pre = test_pre.drop(columns = ['ID'])
test_pre['Customer_care_calls'] = test_pre['Customer_care_calls'].str.replace('$', '').astype('int')

test_pre['Warehouse_block'] = le1.transform(test_pre['Warehouse_block'])
test_pre['Mode_of_Shipment'] = le2.transform(test_pre['Mode_of_Shipment'])
test_pre['Product_importance'] = le3.transform(test_pre['Product_importance'])
test_pre['Gender'] = le4.transform(test_pre['Gender'])

rf_test_predict = rf.predict(test_pre)
result = pd.DataFrame(rf_test_predict, columns = ['pred'])
# result.to_csv('result.csv', index = False)