<a href="https://colab.research.google.com/github/JonghyeonWon/20261RCOSE32200/blob/main/subject1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = 'https://raw.githubusercontent.com/Datamanim/datarepo/refs/heads/main/data/3.csv'
df = pd.read_csv(data)
df

     c  S     I       F  Age      Salary     max
0    B  Y  21.0  27.525   47   36850.09원  BX_etq
1    A  X  81.0   2.739   23         NaN  OQ_bpz
2    A  X  30.0  11.537   18  105970.72원  ZX_lfw
3    C  Z   NaN  30.674   40   59489.16원  PX_saq
4    C  Z  20.0  23.070   48   68921.15원  XL_nez
5    C  X  59.0  29.968   25   40061.44원  GQ_xdb
6  NaN  Z  20.0  16.814   29   37604.44원  HK_bgp
7    A  Y   2.0  79.284   54    33592.8원  GU_ixm
8    A  X  53.0  79.121   54   95753.08원  CM_drg
9    B  Z   9.0  23.040   38  114928.74원  GE_jfx

In [3]:
df.groupby(['S'])[['I','F']].mean()

           I         F
S
X  55.750000  30.84125
Y  11.500000  53.40450
Z  16.333333  23.39950

In [4]:
df['age_period'] = df['Age'] // 10 * 10

In [8]:
df_test = df[['S','F','I']]

In [9]:
df_test.pivot_table(index = 'S', columns = 'I', values = 'F')

I    2.0    9.0     20.0    21.0    30.0    53.0    59.0   81.0
S
X     NaN    NaN     NaN     NaN  11.537  79.121  29.968  2.739
Y  79.284    NaN     NaN  27.525     NaN     NaN     NaN    NaN
Z     NaN  23.04  19.942     NaN     NaN     NaN     NaN    NaN

In [10]:
pd.crosstab(df['S'], df['age_period'])

age_period  10  20  30  40  50
S
X            1   2   0   0   1
Y            0   0   0   1   1
Z            0   1   1   2   0

In [11]:
df1 = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/refs/heads/main/data/4.csv')
df2 = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/refs/heads/main/data/5.csv')

In [12]:
df1

   ID     Name  Score
0   1    Alice     85
1   2      Bob     90
2   3  Charlie     95
3   4    David     80

In [13]:
df2

   ID     Name  Age
0   3  Charlie   23
1   4    David   24
2   5   Edward   25
3   6    Fiona   22

In [16]:
pd.concat([df1, df2]).reset_index(drop=True)

   ID     Name  Score   Age
0   1    Alice   85.0   NaN
1   2      Bob   90.0   NaN
2   3  Charlie   95.0   NaN
3   4    David   80.0   NaN
4   3  Charlie    NaN  23.0
5   4    David    NaN  24.0
6   5   Edward    NaN  25.0
7   6    Fiona    NaN  22.0

In [15]:
pd.merge(df1, df2)

   ID     Name  Score  Age
0   3  Charlie     95   23
1   4    David     80   24

In [17]:
pd.merge(df1,df2,how='outer')

   ID     Name  Score   Age
0   1    Alice   85.0   NaN
1   2      Bob   90.0   NaN
2   3  Charlie   95.0  23.0
3   4    David   80.0  24.0
4   5   Edward    NaN  25.0
5   6    Fiona    NaN  22.0

In [18]:
df

     c  S     I       F  Age      Salary     max  age_period
0    B  Y  21.0  27.525   47   36850.09원  BX_etq          40
1    A  X  81.0   2.739   23         NaN  OQ_bpz          20
2    A  X  30.0  11.537   18  105970.72원  ZX_lfw          10
3    C  Z   NaN  30.674   40   59489.16원  PX_saq          40
4    C  Z  20.0  23.070   48   68921.15원  XL_nez          40
5    C  X  59.0  29.968   25   40061.44원  GQ_xdb          20
6  NaN  Z  20.0  16.814   29   37604.44원  HK_bgp          20
7    A  Y   2.0  79.284   54    33592.8원  GU_ixm          50
8    A  X  53.0  79.121   54   95753.08원  CM_drg          50
9    B  Z   9.0  23.040   38  114928.74원  GE_jfx          30

In [19]:
pd.get_dummies(df[['S']]) # one-hot encoding

     S_X    S_Y    S_Z
0  False   True  False
1   True  False  False
2   True  False  False
3  False  False   True
4  False  False   True
5   True  False  False
6  False  False   True
7  False   True  False
8   True  False  False
9  False  False   True

In [20]:
# 시계열 데이터 형식 변환
data = {
    'date': [
        '2023-01-01',     # 정상적인 날짜 형식 (YYYY-MM-DD)
        '01/02/2023',     # 다른 형식의 날짜 (MM/DD/YYYY)
        '2023.03.03',     # 점(.)으로 구분된 날짜 (YYYY.MM.DD)
        'april 4, 2023',  # 문자로 표현된 날짜 (Month Day, Year)
        '2023/05/05',     # 슬래시(/)로 구분된 날짜 (YYYY/MM/DD)
        '06-06-2023',     # 하이픈(-)으로 구분된 날짜 (MM-DD-YYYY)
        '2023-07-32',     # 잘못된 날짜 (7월에 32일 없음)
        'random text',    # 완전히 잘못된 값
        '',               # 빈 문자열
        None              # None 값 (결측치)
    ]
}

In [21]:
df = pd.DataFrame(data)

In [22]:
df

            date
0     2023-01-01
1     01/02/2023
2     2023.03.03
3  april 4, 2023
4     2023/05/05
5     06-06-2023
6     2023-07-32
7    random text
8
9           None

In [23]:
pd.to_datetime(df['date'], errors='coerce')

0   2023-01-01
1          NaT
2          NaT
3          NaT
4          NaT
5          NaT
6          NaT
7          NaT
8          NaT
9          NaT
Name: date, dtype: datetime64[ns]

In [24]:
new_df = pd.concat([df, pd.to_datetime(df['date'],errors='coerce')], axis=1)

In [26]:
new_df.columns = ['기존','변경 후']
new_df

              기존       변경 후
0     2023-01-01 2023-01-01
1     01/02/2023        NaT
2     2023.03.03        NaT
3  april 4, 2023        NaT
4     2023/05/05        NaT
5     06-06-2023        NaT
6     2023-07-32        NaT
7    random text        NaT
8                       NaT
9           None        NaT

In [27]:
data2 ='https://raw.githubusercontent.com/Datamanim/datarepo/refs/heads/main/data/6.csv'

In [28]:
df = pd.read_csv(data2)
df

,datetime,st,sample1,sample2
0,2023-04-18 04:00:00,2023-04-18 04:00:00,2023-04-18_04:00:00,2023-04-18 04시
1,2023-07-31 19:00:00,2023-07-31 19:00:00,2023-07-31_19:00:00,2023-07-31 19시
2,2023-08-07 10:00:00,2023-08-07 10:00:00,2023-08-07_10:00:00,2023-08-07 10시
3,2023-01-02 06:00:00,2023-01-02 06:00:00,2023-01-02_06:00:00,2023-01-02 06시
4,2023-07-29 17:00:00,2023-07-29 17:00:00,2023-07-29_17:00:00,2023-07-29 17시
5,2023-02-13 01:00:00,2023-02-13 01:00:00,2023-02-13_01:00:00,2023-02-13 01시
6,2023-12-14 21:00:00,2023-12-14 21:00:00,2023-12-14_21:00:00,2023-12-14 21시
7,2023-03-29 16:00:00,2023-03-29 16:00:00,2023-03-29_16:00:00,2023-03-29 16시
8,2023-08-15 01:00:00,2023-08-15 01:00:00,2023-08-15_01:00:00,2023-08-15 01시
9,2023-08-22 11:00:00,2023-08-22 11:00:00,2023-08-22_11:00:00,2023-08-22 11시
10,2023-01-01 20:00:00,2023-01-01 20:00:00,2023-01-01_20:00:00,2023-01-01 20시
11,2023-05-21 23:00:00,2023-05-21 23:00:00,2023-05-21_23:00:00,2023-05-21 23시
12,2023-11-21 06:00:00,2023-11-21 06:00:00,2023-11-21_06:00:00,2023-11-21 06시
13,2023-04-11 10:00:00,2023-04-11 10:00:00,2023-04-11_10:00:00,2023-04-11 10시
14,2023-04-23 19:00:00,2023-04-23 19:00:00,2023-04-23_19:00:00,2023-04-23 19시
15,2023-08-11 16:00:00,2023-08-11 16:00:00,2023-08-11_16:00:00,2023-08-11 16시
16,2023-07-13 16:00:00,2023-07-13 16:00:00,2023-07-13_16:00:00,2023-07-13 16시
17,2024-02-05 03:00:00,2024-02-05 03:00:00,2024-02-05_03:00:00,2024-02-05 03시
18,2023-05-18 08:00:00,2023-05-18 08:00:00,2023-05-18_08:00:00,2023-05-18 08시
19,2023-12-03 18:00:00,2023-12-03 18:00:00,2023-12-03_18:00:00,2023-12-03 18시
20,2023-04-05 05:00:00,2023-04-05 05:00:00,2023-04-05_05:00:00,2023-04-05 05시
21,2023-02-07 15:00:00,2023-02-07 15:00:00,2023-02-07_15:00:00,2023-02-07 15시
22,2023-08-21 09:00:00,2023-08-21 09:00:00,2023-08-21_09:00:00,2023-08-21 09시
23,2023-05-13 18:00:00,2023-05-13 18:00:00,2023-05-13_18:00:00,2023-05-13 18시
24,2023-04-04 04:00:00,2023-04-04 04:00:00,2023-04-04_04:00:00,2023-04-04 04시
25,2023-12-09 00:00:00,2023-12-09 00:00:00,2023-12-09_00:00:00,2023-12-09 00시
26,2023-07-05 13:00:00,2023-07-05 13:00:00,2023-07-05_13:00:00,2023-07-05 13시
27,2023-10-09 06:00:00,2023-10-09 06:00:00,2023-10-09_06:00:00,2023-10-09 06시
28,2023-08-19 22:00:00,2023-08-19 22:00:00,2023-08-19_22:00:00,2023-08-19 22시
29,2023-05-06 10:00:00,2023-05-06 10:00:00,2023-05-06_10:00:00,2023-05-06 10시

In [32]:
df['datetime'] = pd.to_datetime(df['datetime'])
df['st'] = pd.to_datetime(df['st'])

In [36]:
df['sample1'] = pd.to_datetime(df['sample1'], format = '%Y-%m-%d_%H:%M:%S')

In [39]:
df['sample2'] = pd.to_datetime(df['sample2'], format = '%Y-%m-%d %H시')

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  30 non-null     datetime64[ns]
 1   st        30 non-null     datetime64[ns]
 2   sample1   30 non-null     datetime64[ns]
 3   sample2   30 non-null     datetime64[ns]
dtypes: datetime64[ns](4)
memory usage: 1.1 KB

In [41]:
# 사용 가능한 .dt 메소드
df['dates'].dt.year         # 연도 추출
df['dates'].dt.month        # 월 추출
df['dates'].dt.day          # 일 추출
df['dates'].dt.hour         # 시간 추출
df['dates'].dt.minute       # 분 추출
df['dates'].dt.second       # 초 추출
df['dates'].dt.weekday      # 요일(0=월요일, 6=일요일) 추출
df['dates'].dt.dayofweek    # 요일(0=월요일, 6=일요일) 추출 (weekday와 동일)
df['dates'].dt.dayofyear    # 연도의 몇 번째 날인지 추출
df['dates'].dt.quarter      # 분기 추출
df['dates'].dt.strftime('%Y-%m-%d')  # 포맷에 맞춰 문자열로 변환
df['dates'].dt.to_period('M')  # 주기(period)로 변환 (예: 월 단위)

KeyError: 'dates'