<a href="https://colab.research.google.com/github/JonghyeonWon/20261RCOSE32200/blob/main/subject2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

from sklearn.metrics import roc_auc_score, f1_score, mean_absolute_error, mean_squared_error

In [ ]:
# 파일 저장: df.to_csv()

In [ ]:
# 분류
# 레이블 예측 (predict)
# 확률 예측 (predict_proba)

In [4]:
# 회귀
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from xgboost import XGBRegressor, XGBClassifier

rf = RandomForestClassifier()
rf.fit(x_train)
rf.predict(x_test) # 회귀, 분류 레이블
rf.predict_proba(x_test)[:,1] # 확률 예측

In [ ]:
predict = rf.predict(x_test)
predict_df = pd.DataFrame(predict, columns = ['pred'])
predict_df.to_csv('result.csv',index = False)

In [5]:
train_url = 'https://raw.githubusercontent.com/Datamanim/datarepo/refs/heads/main/data/customer_train.csv'
test_url  = 'https://raw.githubusercontent.com/Datamanim/datarepo/refs/heads/main/data/customer_test.csv'
import pandas as pd

In [6]:
train = pd.read_csv(train_url)
test= pd.read_csv(test_url)

In [7]:
train.head()

,회원ID,총구매액,최대구매액,환불금액,주구매상품,주구매지점,방문일수,방문당구매건수,주말방문비율,구매주기,성별
0,0,68282840,11264000,6860000.0,기타,강남점,19,3.894737,0.527027,17,0
1,1,2136000,2136000,300000.0,스포츠,잠실점,2,1.500000,0.000000,1,0
2,2,3197000,1639000,NaN,남성 캐주얼,관악점,2,2.000000,0.000000,1,1
3,3,16077620,4935000,NaN,기타,광주점,18,2.444444,0.318182,16,1
4,4,29050000,24000000,NaN,보석,본 점,2,1.500000,0.000000,85,0

In [8]:
test.head()

,회원ID,총구매액,최대구매액,환불금액,주구매상품,주구매지점,방문일수,방문당구매건수,주말방문비율,구매주기
0,3500,70900400,22000000,4050000.0,골프,부산본점,13,1.461538,0.789474,26
1,3501,310533100,38558000,48034700.0,농산물,잠실점,90,2.433333,0.369863,3
2,3502,305264140,14825000,30521000.0,가공식품,본 점,101,14.623762,0.083277,3
3,3503,7594080,5225000,NaN,주방용품,부산본점,5,2.000000,0.000000,47
4,3504,1795790,1411200,NaN,수산품,청량리점,3,2.666667,0.125000,8

In [11]:
train.shape

(3500, 11)

In [12]:
test.shape

(2482, 10)

In [13]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   회원ID     3500 non-null   int64
 1   총구매액     3500 non-null   int64
 2   최대구매액    3500 non-null   int64
 3   환불금액     1205 non-null   float64
 4   주구매상품    3500 non-null   object
 5   주구매지점    3500 non-null   object
 6   방문일수     3500 non-null   int64
 7   방문당구매건수  3500 non-null   float64
 8   주말방문비율   3500 non-null   float64
 9   구매주기     3500 non-null   int64
 10  성별       3500 non-null   int64
dtypes: float64(3), int64(6), object(2)
memory usage: 300.9+ KB

In [14]:
train.nunique()

회원ID       3500
총구매액       3396
최대구매액      2576
환불금액       1114
주구매상품        42
주구매지점        24
방문일수        147
방문당구매건수    1107
주말방문비율     1142
구매주기        135
성별            2
dtype: int64

In [15]:
train.isnull().sum()

회원ID          0
총구매액          0
최대구매액         0
환불금액       2295
주구매상품         0
주구매지점         0
방문일수          0
방문당구매건수       0
주말방문비율        0
구매주기          0
성별            0
dtype: int64

In [16]:
train.select_dtypes(include = 'object')

       주구매상품 주구매지점
0         기타   강남점
1        스포츠   잠실점
2     남성 캐주얼   관악점
3         기타   광주점
4         보석  본  점
...      ...   ...
3495      골프  본  점
3496    시티웨어  부산본점
3497    주방용품   창원점
3498     화장품  본  점
3499      기타  본  점

[3500 rows x 2 columns]

In [17]:
train.select_dtypes(exclude='object').describe()

,회원ID,총구매액,최대구매액,환불금액,방문일수,방문당구매건수,주말방문비율,구매주기,성별
count,3500.000000,3.500000e+03,3.500000e+03,1.205000e+03,3500.000000,3500.000000,3500.000000,3500.000000,3500.000000
mean,1749.500000,9.191925e+07,1.966424e+07,2.407822e+07,19.253714,2.834963,0.307246,20.958286,0.376000
std,1010.507298,1.635065e+08,3.199235e+07,4.746453e+07,27.174942,1.912368,0.289752,24.748682,0.484449
min,0.000000,-5.242152e+07,-2.992000e+06,5.600000e+03,1.000000,1.000000,0.000000,0.000000,0.000000
25%,874.750000,4.747050e+06,2.875000e+06,2.259000e+06,2.000000,1.666667,0.027291,4.000000,0.000000
50%,1749.500000,2.822270e+07,9.837000e+06,7.392000e+06,8.000000,2.333333,0.256410,13.000000,0.000000
75%,2624.250000,1.065079e+08,2.296250e+07,2.412000e+07,25.000000,3.375000,0.448980,28.000000,1.000000
max,3499.000000,2.323180e+09,7.066290e+08,5.637530e+08,285.000000,22.083333,1.000000,166.000000,1.000000

In [18]:
remove_col = ['회원ID', '환불금액']
train_preprocessing = train.copy()
train_preprocessing = train_preprocessing.drop(columns = remove_col)

           총구매액     최대구매액   주구매상품 주구매지점  방문일수   방문당구매건수    주말방문비율  구매주기  성별
0      68282840  11264000      기타   강남점    19  3.894737  0.527027    17   0
1       2136000   2136000     스포츠   잠실점     2  1.500000  0.000000     1   0
2       3197000   1639000  남성 캐주얼   관악점     2  2.000000  0.000000     1   1
3      16077620   4935000      기타   광주점    18  2.444444  0.318182    16   1
4      29050000  24000000      보석  본  점     2  1.500000  0.000000    85   0
...         ...       ...     ...   ...   ...       ...       ...   ...  ..
3495    3175200   3042900      골프  본  점     1  2.000000  1.000000     0   1
3496   29628600   7200000    시티웨어  부산본점     8  1.625000  0.461538    40   1
3497      75000     75000    주방용품   창원점     1  1.000000  0.000000     0   0
3498    1875000   1000000     화장품  본  점     2  1.000000  0.000000    39   0
3499  263101550  34632000      기타  본  점    38  2.421053  0.467391     8   0

[3500 rows x 9 columns]

In [26]:
# '범주형'에 대해서 인코딩 필요
# pd.get_dummies(train_preprocessing)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(train_preprocessing['주구매상품'])

le2 = LabelEncoder()
le2.fit(train_preprocessing['주구매지점'])

LabelEncoder()

In [27]:
le_predict = le.transform(train_preprocessing['주구매상품'])
le_predict2 = le2.transform(train_preprocessing['주구매지점'])
train_preprocessing['주구매상품'] = le_predict
train_preprocessing['주구매지점'] = le_predict2
train_preprocessing

           총구매액     최대구매액  주구매상품  주구매지점  방문일수   방문당구매건수    주말방문비율  구매주기  성별
0      68282840  11264000      5      0    19  3.894737  0.527027    17   0
1       2136000   2136000     21     19     2  1.500000  0.000000     1   0
2       3197000   1639000      6      1     2  2.000000  0.000000     1   1
3      16077620   4935000      5      2    18  2.444444  0.318182    16   1
4      29050000  24000000     15      8     2  1.500000  0.000000    85   0
...         ...       ...    ...    ...   ...       ...       ...   ...  ..
3495    3175200   3042900      3      8     1  2.000000  1.000000     0   1
3496   29628600   7200000     22      9     8  1.625000  0.461538    40   1
3497      75000     75000     32     21     1  1.000000  0.000000     0   0
3498    1875000   1000000     41      8     2  1.000000  0.000000    39   0
3499  263101550  34632000      5      8    38  2.421053  0.467391     8   0

[3500 rows x 9 columns]

In [23]:
train_preprocessing['주구매상품'].unique()

array([ 5, 21,  6, 15, 11, 22, 13,  9, 41,  3,  4,  0, 20, 24, 33, 36, 17,
       27, 34, 29, 26, 40, 28, 31, 32,  2,  1, 30, 14,  7, 18,  8, 16, 39,
       12, 37, 35, 10, 38, 23, 19, 25])

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
scaled_df = train_preprocessing[['총구매액','최대구매액','방문일수','방문당구매건수','구매주기']]
sc = StandardScaler()
sc.fit(scaled_df)

StandardScaler()

In [30]:
sc.transform(scaled_df)

array([[-0.14458009, -0.26260786, -0.00933767,  0.55424743, -0.15996211],
       [-0.54918957, -0.54796686, -0.63500336, -0.69816782, -0.80655356],
       [-0.5426996 , -0.56350404, -0.63500336, -0.43667453, -0.80655356],
       ...,
       [-0.56179637, -0.61239772, -0.67180723, -0.95966112, -0.84696552],
       [-0.55078606, -0.58348042, -0.63500336, -0.95966112,  0.72910114],
       [ 1.04709431,  0.46792117,  0.68993576, -0.21646965, -0.5236698 ]])

In [34]:
train_preprocessing.loc[:,['총구매액','최대구매액','방문일수','방문당구매건수','구매주기']] = sc.transform(scaled_df)
train_preprocessing

,총구매액,최대구매액,주구매상품,주구매지점,방문일수,방문당구매건수,주말방문비율,구매주기,성별
0,-0.144580,-0.262608,5,0,-0.009338,0.554247,0.527027,-0.159962,0
1,-0.549190,-0.547967,21,19,-0.635003,-0.698168,0.000000,-0.806554,0
2,-0.542700,-0.563504,6,1,-0.635003,-0.436675,0.000000,-0.806554,1
3,-0.463911,-0.460465,5,2,-0.046142,-0.204236,0.318182,-0.200374,1
4,-0.384561,0.135544,15,8,-0.635003,-0.698168,0.000000,2.588052,0
...,...,...,...,...,...,...,...,...,...
3495,-0.542833,-0.519615,3,8,-0.671807,-0.436675,1.000000,-0.846966,1
3496,-0.381022,-0.389656,22,9,-0.414180,-0.632794,0.461538,0.769513,1
3497,-0.561796,-0.612398,32,21,-0.671807,-0.959661,0.000000,-0.846966,0
3498,-0.550786,-0.583480,41,8,-0.635003,-0.959661,0.000000,0.729101,0
3499,1.047094,0.467921,5,8,0.689936,-0.216470,0.467391,-0.523670,0

In [38]:
y = train_preprocessing['성별']
x = train_preprocessing.drop(columns = '성별')

In [39]:
from sklearn.model_selection import train_test_split

In [41]:
x_train, x_validation, y_train, y_validation = train_test_split(x, y, test_size = 0.3, random_state = 42)