<a href="https://colab.research.google.com/github/JonghyeonWon/20261RCOSE32200/blob/main/subject1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = 'https://raw.githubusercontent.com/Datamanim/datarepo/refs/heads/main/data/3.csv'
df = pd.read_csv(data)
df

     c  S     I       F  Age      Salary     max
0    B  Y  21.0  27.525   47   36850.09원  BX_etq
1    A  X  81.0   2.739   23         NaN  OQ_bpz
2    A  X  30.0  11.537   18  105970.72원  ZX_lfw
3    C  Z   NaN  30.674   40   59489.16원  PX_saq
4    C  Z  20.0  23.070   48   68921.15원  XL_nez
5    C  X  59.0  29.968   25   40061.44원  GQ_xdb
6  NaN  Z  20.0  16.814   29   37604.44원  HK_bgp
7    A  Y   2.0  79.284   54    33592.8원  GU_ixm
8    A  X  53.0  79.121   54   95753.08원  CM_drg
9    B  Z   9.0  23.040   38  114928.74원  GE_jfx

In [4]:
df2 = df.copy()
df2

     c  S     I       F  Age      Salary     max
0    B  Y  21.0  27.525   47   36850.09원  BX_etq
1    A  X  81.0   2.739   23         NaN  OQ_bpz
2    A  X  30.0  11.537   18  105970.72원  ZX_lfw
3    C  Z   NaN  30.674   40   59489.16원  PX_saq
4    C  Z  20.0  23.070   48   68921.15원  XL_nez
5    C  X  59.0  29.968   25   40061.44원  GQ_xdb
6  NaN  Z  20.0  16.814   29   37604.44원  HK_bgp
7    A  Y   2.0  79.284   54    33592.8원  GU_ixm
8    A  X  53.0  79.121   54   95753.08원  CM_drg
9    B  Z   9.0  23.040   38  114928.74원  GE_jfx

In [5]:
df.drop(columns = ['S'])

     c     I       F  Age      Salary     max
0    B  21.0  27.525   47   36850.09원  BX_etq
1    A  81.0   2.739   23         NaN  OQ_bpz
2    A  30.0  11.537   18  105970.72원  ZX_lfw
3    C   NaN  30.674   40   59489.16원  PX_saq
4    C  20.0  23.070   48   68921.15원  XL_nez
5    C  59.0  29.968   25   40061.44원  GQ_xdb
6  NaN  20.0  16.814   29   37604.44원  HK_bgp
7    A   2.0  79.284   54    33592.8원  GU_ixm
8    A  53.0  79.121   54   95753.08원  CM_drg
9    B   9.0  23.040   38  114928.74원  GE_jfx

df.drop_duplicates()

In [8]:
df.dropna()

     c  S     I       F  Age      Salary     max
0    B  Y  21.0  27.525   47   36850.09원  BX_etq
2    A  X  30.0  11.537   18  105970.72원  ZX_lfw
4    C  Z  20.0  23.070   48   68921.15원  XL_nez
5    C  X  59.0  29.968   25   40061.44원  GQ_xdb
7    A  Y   2.0  79.284   54    33592.8원  GU_ixm
8    A  X  53.0  79.121   54   95753.08원  CM_drg
9    B  Z   9.0  23.040   38  114928.74원  GE_jfx

In [9]:
df.fillna('fillna_test')

             c  S            I       F  Age       Salary     max
0            B  Y         21.0  27.525   47    36850.09원  BX_etq
1            A  X         81.0   2.739   23  fillna_test  OQ_bpz
2            A  X         30.0  11.537   18   105970.72원  ZX_lfw
3            C  Z  fillna_test  30.674   40    59489.16원  PX_saq
4            C  Z         20.0  23.070   48    68921.15원  XL_nez
5            C  X         59.0  29.968   25    40061.44원  GQ_xdb
6  fillna_test  Z         20.0  16.814   29    37604.44원  HK_bgp
7            A  Y          2.0  79.284   54     33592.8원  GU_ixm
8            A  X         53.0  79.121   54    95753.08원  CM_drg
9            B  Z          9.0  23.040   38   114928.74원  GE_jfx

In [19]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
# ffill: 앞의 행으로 결측치 채우기
# bfill: 뒤의 행으로 결측치 채우기
df

     c  S     I       F  Age         Salary     max
0    B  Y  21.0  27.525   47   36850.090000  BX_etq
1    A  X  81.0   2.739   23   65907.957778  OQ_bpz
2    A  X  30.0  11.537   18  105970.720000  ZX_lfw
3    C  Z   NaN  30.674   40   59489.160000  PX_saq
4    C  Z  20.0  23.070   48   68921.150000  XL_nez
5    C  X  59.0  29.968   25   40061.440000  GQ_xdb
6  NaN  Z  20.0  16.814   29   37604.440000  HK_bgp
7    A  Y   2.0  79.284   54   33592.800000  GU_ixm
8    A  X  53.0  79.121   54   95753.080000  CM_drg
9    B  Z   9.0  23.040   38  114928.740000  GE_jfx

In [20]:
df.rename(columns = {'S':'SS'})

     c SS     I       F  Age         Salary     max
0    B  Y  21.0  27.525   47   36850.090000  BX_etq
1    A  X  81.0   2.739   23   65907.957778  OQ_bpz
2    A  X  30.0  11.537   18  105970.720000  ZX_lfw
3    C  Z   NaN  30.674   40   59489.160000  PX_saq
4    C  Z  20.0  23.070   48   68921.150000  XL_nez
5    C  X  59.0  29.968   25   40061.440000  GQ_xdb
6  NaN  Z  20.0  16.814   29   37604.440000  HK_bgp
7    A  Y   2.0  79.284   54   33592.800000  GU_ixm
8    A  X  53.0  79.121   54   95753.080000  CM_drg
9    B  Z   9.0  23.040   38  114928.740000  GE_jfx

In [21]:
df.reset_index(drop=True)

     c  S     I       F  Age         Salary     max
0    B  Y  21.0  27.525   47   36850.090000  BX_etq
1    A  X  81.0   2.739   23   65907.957778  OQ_bpz
2    A  X  30.0  11.537   18  105970.720000  ZX_lfw
3    C  Z   NaN  30.674   40   59489.160000  PX_saq
4    C  Z  20.0  23.070   48   68921.150000  XL_nez
5    C  X  59.0  29.968   25   40061.440000  GQ_xdb
6  NaN  Z  20.0  16.814   29   37604.440000  HK_bgp
7    A  Y   2.0  79.284   54   33592.800000  GU_ixm
8    A  X  53.0  79.121   54   95753.080000  CM_drg
9    B  Z   9.0  23.040   38  114928.740000  GE_jfx

In [26]:
df.sort_values(['S', 'I'],ascending=[True, False]).reset_index(drop=True)

     c  S     I       F  Age         Salary     max
0    A  X  81.0   2.739   23   65907.957778  OQ_bpz
1    C  X  59.0  29.968   25   40061.440000  GQ_xdb
2    A  X  53.0  79.121   54   95753.080000  CM_drg
3    A  X  30.0  11.537   18  105970.720000  ZX_lfw
4    B  Y  21.0  27.525   47   36850.090000  BX_etq
5    A  Y   2.0  79.284   54   33592.800000  GU_ixm
6    C  Z  20.0  23.070   48   68921.150000  XL_nez
7  NaN  Z  20.0  16.814   29   37604.440000  HK_bgp
8    B  Z   9.0  23.040   38  114928.740000  GE_jfx
9    C  Z   NaN  30.674   40   59489.160000  PX_saq

In [28]:
df['Age'].map(lambda x : x + 1)

0    48
1    24
2    19
3    41
4    49
5    26
6    30
7    55
8    55
9    39
Name: Age, dtype: int64

In [29]:
data = 'https://raw.githubusercontent.com/Datamanim/datarepo/refs/heads/main/data/3.csv'
df = pd.read_csv(data)
df

     c  S     I       F  Age      Salary     max
0    B  Y  21.0  27.525   47   36850.09원  BX_etq
1    A  X  81.0   2.739   23         NaN  OQ_bpz
2    A  X  30.0  11.537   18  105970.72원  ZX_lfw
3    C  Z   NaN  30.674   40   59489.16원  PX_saq
4    C  Z  20.0  23.070   48   68921.15원  XL_nez
5    C  X  59.0  29.968   25   40061.44원  GQ_xdb
6  NaN  Z  20.0  16.814   29   37604.44원  HK_bgp
7    A  Y   2.0  79.284   54    33592.8원  GU_ixm
8    A  X  53.0  79.121   54   95753.08원  CM_drg
9    B  Z   9.0  23.040   38  114928.74원  GE_jfx

In [31]:
# S값이 x, Age가 20이상인 경우
def age_preprocessing(x):
  age = x['Age']
  s = x['S']
  if s =='X' and age >= 20:
    return 'qqq'
  else:
    return 'rrr'

df['age_period_apply'] = df[['Age', 'S']].apply(age_preprocessing, axis = 1)
df

     c  S     I       F  Age      Salary     max age_period_apply
0    B  Y  21.0  27.525   47   36850.09원  BX_etq              rrr
1    A  X  81.0   2.739   23         NaN  OQ_bpz              qqq
2    A  X  30.0  11.537   18  105970.72원  ZX_lfw              rrr
3    C  Z   NaN  30.674   40   59489.16원  PX_saq              rrr
4    C  Z  20.0  23.070   48   68921.15원  XL_nez              rrr
5    C  X  59.0  29.968   25   40061.44원  GQ_xdb              qqq
6  NaN  Z  20.0  16.814   29   37604.44원  HK_bgp              rrr
7    A  Y   2.0  79.284   54    33592.8원  GU_ixm              rrr
8    A  X  53.0  79.121   54   95753.08원  CM_drg              qqq
9    B  Z   9.0  23.040   38  114928.74원  GE_jfx              rrr