<a href="https://colab.research.google.com/github/JonghyeonWon/20261RCOSE32200/blob/main/subject1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
pd

In [ ]:
# Series: 1차원 배열 구조
# DataFrame: 2차원 배열 구조
fruits = pd.Series(['사과', '바나나', '체리'])
print(fruits)

0     사과
1    바나나
2     체리
dtype: object

In [ ]:
print(fruits.index)

RangeIndex(start=0, stop=3, step=1)

In [ ]:
print(fruits.values)

['사과' '바나나' '체리']

In [ ]:
fruits.values[2]

'체리'

In [ ]:
data2 = [['사과',10],['바나나',5],['체리',20]]
df = pd.DataFrame(data2)
print(df)

     0   1
0   사과  10
1  바나나   5
2   체리  20

In [ ]:
data = {
    '과일':['사과','바나나','체리'],
    '수량':[10,5,20]
}
df = pd.DataFrame(data)
df

    과일  수량
0   사과  10
1  바나나   5
2   체리  20

In [ ]:
df['과일']

0     사과
1    바나나
2     체리
Name: 과일, dtype: object

In [ ]:
df2 = pd.DataFrame(data2)

In [ ]:
type(df2)

pandas.core.frame.DataFrame

In [ ]:
df2

     0   1
0   사과  10
1  바나나   5
2   체리  20

In [ ]:
df2.columns = ['과일','수량']
df

    과일  수량
0   사과  10
1  바나나   5
2   체리  20

In [ ]:
# pd.read_csv(path): csv 파일 읽기
# pd.read_execl: excel 파일 읽기
# csv파일: ','를 기준으로 구분 된 데이터

data = 'https://raw.githubusercontent.com/Datamanim/datarepo/refs/heads/main/data/1.csv'
df = pd.read_csv(data, index_col = 0)
# or df.drop(columns = ['Unnamed: 0']) 실행

In [ ]:
df

        이름  나이   도시
0    Alice  25   서울
1      Bob  30   부산
2  Charlie  35  NaN

In [ ]:
data = 'https://raw.githubusercontent.com/Datamanim/datarepo/refs/heads/main/data/2.csv'

In [ ]:
pd.read_csv(data)

      이름\t나이\t도시
0  Alice\t25\t서울
1    Bob\t30\t부산
2  Charlie\t35\t

In [ ]:
pd.read_csv(data, sep='\t')

        이름  나이   도시
0    Alice  25   서울
1      Bob  30   부산
2  Charlie  35  NaN

In [ ]:
data = 'https://raw.githubusercontent.com/Datamanim/datarepo/refs/heads/main/data/3.csv'

In [ ]:
df = pd.read_csv(data)
df

     c  S     I       F  Age      Salary     max
0    B  Y  21.0  27.525   47   36850.09원  BX_etq
1    A  X  81.0   2.739   23         NaN  OQ_bpz
2    A  X  30.0  11.537   18  105970.72원  ZX_lfw
3    C  Z   NaN  30.674   40   59489.16원  PX_saq
4    C  Z  20.0  23.070   48   68921.15원  XL_nez
5    C  X  59.0  29.968   25   40061.44원  GQ_xdb
6  NaN  Z  20.0  16.814   29   37604.44원  HK_bgp
7    A  Y   2.0  79.284   54    33592.8원  GU_ixm
8    A  X  53.0  79.121   54   95753.08원  CM_drg
9    B  Z   9.0  23.040   38  114928.74원  GE_jfx

In [ ]:
df.head(2)

     c  S     I       F  Age     Salary     max
0    B  Y  21.0  27.525   47  36850.09원  BX_etq
1    A  X  81.0   2.739   23        NaN  OQ_bpz

In [ ]:
df.values[0][0]

'  B'

In [ ]:
df.S[1] # 사용 추천 X

'X'

In [ ]:
df['S'][2]

'X'

In [ ]:
df['max'][3]

'PX_saq'

In [ ]:
df[['S','I']]

   S     I
0  Y  21.0
1  X  81.0
2  X  30.0
3  Z   NaN
4  Z  20.0
5  X  59.0
6  Z  20.0
7  Y   2.0
8  X  53.0
9  Z   9.0

In [ ]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [ ]:
df.index = ['a','b','c','d','e','f','g','h','i','j']
df.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

In [ ]:
print(df.index.name)

None

In [ ]:
df.index.name = 'test'

In [ ]:
df

        c  S     I       F  Age      Salary     max
test
a       B  Y  21.0  27.525   47   36850.09원  BX_etq
b       A  X  81.0   2.739   23         NaN  OQ_bpz
c       A  X  30.0  11.537   18  105970.72원  ZX_lfw
d       C  Z   NaN  30.674   40   59489.16원  PX_saq
e       C  Z  20.0  23.070   48   68921.15원  XL_nez
f       C  X  59.0  29.968   25   40061.44원  GQ_xdb
g     NaN  Z  20.0  16.814   29   37604.44원  HK_bgp
h       A  Y   2.0  79.284   54    33592.8원  GU_ixm
i       A  X  53.0  79.121   54   95753.08원  CM_drg
j       B  Z   9.0  23.040   38  114928.74원  GE_jfx

In [ ]:
df.columns

Index(['c', 'S', 'I', 'F', 'Age', 'Salary', 'max'], dtype='object')

In [ ]:
df.iloc[0:3,2:5]

         I       F  Age
test
a     21.0  27.525   47
b     81.0   2.739   23
c     30.0  11.537   18

In [ ]:
df.iloc[0,0]

'  B'

In [ ]:
df.iloc[0,0] = 'A'
df.iloc[0,0]

'A'

In [ ]:
df.loc['c','I']

np.float64(30.0)

In [ ]:
df.isnull()

          c      S      I      F    Age  Salary    max
test
a     False  False  False  False  False   False  False
b     False  False  False  False  False    True  False
c     False  False  False  False  False   False  False
d     False  False   True  False  False   False  False
e     False  False  False  False  False   False  False
f     False  False  False  False  False   False  False
g      True  False  False  False  False   False  False
h     False  False  False  False  False   False  False
i     False  False  False  False  False   False  False
j     False  False  False  False  False   False  False

In [ ]:
df.isnull().sum()

c         1
S         0
I         1
F         0
Age       0
Salary    1
max       0
dtype: int64

In [ ]:
df.isnull().sum().sum()

np.int64(3)

In [ ]:
df == 'B'

          c      S      I      F    Age  Salary    max
test
a     False  False  False  False  False   False  False
b     False  False  False  False  False   False  False
c     False  False  False  False  False   False  False
d     False  False  False  False  False   False  False
e     False  False  False  False  False   False  False
f     False  False  False  False  False   False  False
g     False  False  False  False  False   False  False
h     False  False  False  False  False   False  False
i     False  False  False  False  False   False  False
j      True  False  False  False  False   False  False

In [ ]:
df[df == 'B']

        c    S   I   F  Age Salary  max
test
a     NaN  NaN NaN NaN  NaN    NaN  NaN
b     NaN  NaN NaN NaN  NaN    NaN  NaN
c     NaN  NaN NaN NaN  NaN    NaN  NaN
d     NaN  NaN NaN NaN  NaN    NaN  NaN
e     NaN  NaN NaN NaN  NaN    NaN  NaN
f     NaN  NaN NaN NaN  NaN    NaN  NaN
g     NaN  NaN NaN NaN  NaN    NaN  NaN
h     NaN  NaN NaN NaN  NaN    NaN  NaN
i     NaN  NaN NaN NaN  NaN    NaN  NaN
j       B  NaN NaN NaN  NaN    NaN  NaN

In [ ]:
# s열에서 x,y값을 가지는 데이터만 추출
df['S'].isin(['X','Y'])

test
a     True
b     True
c     True
d    False
e    False
f     True
g    False
h     True
i     True
j    False
Name: S, dtype: bool

In [ ]:
df[df['S'].isin(['X','Y'])]

      c  S     I       F  Age      Salary     max
test
a     A  Y  21.0  27.525   47   36850.09원  BX_etq
b     A  X  81.0   2.739   23         NaN  OQ_bpz
c     A  X  30.0  11.537   18  105970.72원  ZX_lfw
f     C  X  59.0  29.968   25   40061.44원  GQ_xdb
h     A  Y   2.0  79.284   54    33592.8원  GU_ixm
i     A  X  53.0  79.121   54   95753.08원  CM_drg

In [ ]:
df['max'].str.contains('_')

test
a    True
b    True
c    True
d    True
e    True
f    True
g    True
h    True
i    True
j    True
Name: max, dtype: bool

In [ ]:
df[df['max'].str.contains('Q')]

      c  S     I       F  Age     Salary     max
test
b     A  X  81.0   2.739   23        NaN  OQ_bpz
f     C  X  59.0  29.968   25  40061.44원  GQ_xdb

In [ ]:
s = df['c'] == 'A'

In [ ]:
s

test
a     True
b     True
c     True
d    False
e    False
f    False
g    False
h     True
i     True
j    False
Name: c, dtype: bool

In [ ]:
df[s]

      c  S     I       F  Age      Salary     max
test
a     A  Y  21.0  27.525   47   36850.09원  BX_etq
b     A  X  81.0   2.739   23         NaN  OQ_bpz
c     A  X  30.0  11.537   18  105970.72원  ZX_lfw
h     A  Y   2.0  79.284   54    33592.8원  GU_ixm
i     A  X  53.0  79.121   54   95753.08원  CM_drg

In [ ]:
df.loc[s]

      c  S     I       F  Age      Salary     max
test
a     A  Y  21.0  27.525   47   36850.09원  BX_etq
b     A  X  81.0   2.739   23         NaN  OQ_bpz
c     A  X  30.0  11.537   18  105970.72원  ZX_lfw
h     A  Y   2.0  79.284   54    33592.8원  GU_ixm
i     A  X  53.0  79.121   54   95753.08원  CM_drg

In [ ]:
df_filter = df.loc[s]
s1 = df_filter['S'] == 'X'
df_filter.loc[s1]

      c  S     I       F  Age      Salary     max
test
b     A  X  81.0   2.739   23         NaN  OQ_bpz
c     A  X  30.0  11.537   18  105970.72원  ZX_lfw
i     A  X  53.0  79.121   54   95753.08원  CM_drg

In [ ]:
s = df['c'] == 'A'
s1 = df['S'] == 'X'
# and: a & b
# or : a | b
df.loc[s & s1]

      c  S     I       F  Age      Salary     max
test
b     A  X  81.0   2.739   23         NaN  OQ_bpz
c     A  X  30.0  11.537   18  105970.72원  ZX_lfw
i     A  X  53.0  79.121   54   95753.08원  CM_drg

In [ ]:
df.index.name = None
df

     c  S     I       F  Age      Salary     max
a    A  Y  21.0  27.525   47   36850.09원  BX_etq
b    A  X  81.0   2.739   23         NaN  OQ_bpz
c    A  X  30.0  11.537   18  105970.72원  ZX_lfw
d    C  Z   NaN  30.674   40   59489.16원  PX_saq
e    C  Z  20.0  23.070   48   68921.15원  XL_nez
f    C  X  59.0  29.968   25   40061.44원  GQ_xdb
g  NaN  Z  20.0  16.814   29   37604.44원  HK_bgp
h    A  Y   2.0  79.284   54    33592.8원  GU_ixm
i    A  X  53.0  79.121   54   95753.08원  CM_drg
j    B  Z   9.0  23.040   38  114928.74원  GE_jfx

In [ ]:
df.head() # 기본: 상위 5개

   c  S     I       F  Age      Salary     max
a  A  Y  21.0  27.525   47   36850.09원  BX_etq
b  A  X  81.0   2.739   23         NaN  OQ_bpz
c  A  X  30.0  11.537   18  105970.72원  ZX_lfw
d  C  Z   NaN  30.674   40   59489.16원  PX_saq
e  C  Z  20.0  23.070   48   68921.15원  XL_nez

In [ ]:
df.tail() # 기본: 하위 5개

     c  S     I       F  Age      Salary     max
f    C  X  59.0  29.968   25   40061.44원  GQ_xdb
g  NaN  Z  20.0  16.814   29   37604.44원  HK_bgp
h    A  Y   2.0  79.284   54    33592.8원  GU_ixm
i    A  X  53.0  79.121   54   95753.08원  CM_drg
j    B  Z   9.0  23.040   38  114928.74원  GE_jfx

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c       9 non-null      object
 1   S       10 non-null     object
 2   I       9 non-null      float64
 3   F       10 non-null     float64
 4   Age     10 non-null     int64
 5   Salary  9 non-null      object
 6   max     10 non-null     object
dtypes: float64(2), int64(1), object(4)
memory usage: 940.0+ bytes

In [ ]:
df['F'].astype('int')

a    27
b     2
c    11
d    30
e    23
f    29
g    16
h    79
i    79
j    23
Name: F, dtype: int64

In [ ]:
df.describe() # numeric 값에 대한 통계

               I          F        Age
count   9.000000  10.000000  10.000000
mean   32.777778  32.377200  37.600000
std    25.998932  26.132647  13.209424
min     2.000000   2.739000  18.000000
25%    20.000000  18.370500  26.000000
50%    21.000000  25.297500  39.000000
75%    53.000000  30.497500  47.750000
max    81.000000  79.284000  54.000000

In [ ]:
df.T

,a,b,c,d,e,f,g,h,i,j
c,A,A,A,C,C,C,NaN,A,A,B
S,Y,X,X,Z,Z,X,Z,Y,X,Z
I,21.0,81.0,30.0,NaN,20.0,59.0,20.0,2.0,53.0,9.0
F,27.525,2.739,11.537,30.674,23.07,29.968,16.814,79.284,79.121,23.04
Age,47,23,18,40,48,25,29,54,54,38
Salary,36850.09원,NaN,105970.72원,59489.16원,68921.15원,40061.44원,37604.44원,33592.8원,95753.08원,114928.74원
max,BX_etq,OQ_bpz,ZX_lfw,PX_saq,XL_nez,GQ_xdb,HK_bgp,GU_ixm,CM_drg,GE_jfx

In [ ]:
df['F'].round()

a    28.0
b     3.0
c    12.0
d    31.0
e    23.0
f    30.0
g    17.0
h    79.0
i    79.0
j    23.0
Name: F, dtype: float64

In [ ]:
df['S'].unique()

array(['Y', 'X', 'Z'], dtype=object)

In [ ]:
df['S'].nunique()

3

In [ ]:
df['S'].value_counts()

S
X    4
Z    4
Y    2
Name: count, dtype: int64

In [ ]:
df['Age'].min()

18

In [ ]:
df[['I','F','Age']].std()

I      25.998932
F      26.132647
Age    13.209424
dtype: float64

In [ ]:
df['Age'].cumsum()

a     47
b     70
c     88
d    128
e    176
f    201
g    230
h    284
i    338
j    376
Name: Age, dtype: int64

In [ ]:
df.select_dtypes(exclude='object')

      I       F  Age
a  21.0  27.525   47
b  81.0   2.739   23
c  30.0  11.537   18
d   NaN  30.674   40
e  20.0  23.070   48
f  59.0  29.968   25
g  20.0  16.814   29
h   2.0  79.284   54
i  53.0  79.121   54
j   9.0  23.040   38

In [ ]:
df.select_dtypes(include='object')

     c  S      Salary     max
a    A  Y   36850.09원  BX_etq
b    A  X         NaN  OQ_bpz
c    A  X  105970.72원  ZX_lfw
d    C  Z   59489.16원  PX_saq
e    C  Z   68921.15원  XL_nez
f    C  X   40061.44원  GQ_xdb
g  NaN  Z   37604.44원  HK_bgp
h    A  Y    33592.8원  GU_ixm
i    A  X   95753.08원  CM_drg
j    B  Z  114928.74원  GE_jfx